/**
 * Magic sign-in link helpers (issue #259).
 *
 * One shared mechanism powers BOTH transactional emails:
 *   A. the approval email an admin's "Approve" sends to a waitlisted person, and
 *   B. the "or just tap here to sign in" link below the 6-digit code in the OTP
 *      sign-in email.
 *
 * The link itself is generated by Better Auth's magicLink plugin (server +
 * client), which stores a single-use, short-TTL token in the existing
 * `verification` table (no new migration). The plugin's one global
 * `sendMagicLink` callback dispatches on `metadata.flow` to build the right
 * email body. This module holds the PURE pieces that have no DB / Worker
 * dependency so they can be unit-tested in isolation.
 */

/** How the magic link reached the user, used to pick the email body. */
export type MagicLinkFlow = 'approval' | 'otp'

/**
 * Metadata forwarded verbatim into `sendMagicLink` via `signInMagicLink`'s
 * `metadata` arg. `flow` selects the email template; `otp` is only present on
 * the OTP-supplement flow so the same email can show the typed code AND the
 * one-tap link.
 */
export interface MagicLinkMetadata {
  flow: MagicLinkFlow
  /** The 6-digit code, present only when `flow === 'otp'`. */
  otp?: string
}

/** Where an onboarded user lands after a magic link verifies (IA from #273). */
export const ONBOARDED_DESTINATION = '/week' as const
/** Where a brand-new (no household) user lands after verifying. */
export const NEW_USER_DESTINATION = '/onboarding' as const

/**
 * Pure post-sign-in redirect decision. After a magic link verifies, an already
 * onboarded user (has a household) goes straight to their week plan; a new user
 * goes through onboarding first. Matches the new IA from #273 (onboarded ->
 * /week, NOT /app).
 *
 * Note: Better Auth's magicLink plugin distinguishes new-vs-returning by
 * account existence (`newUserCallbackURL` vs `callbackURL`), which is a coarser
 * signal than "has a household". We pass BOTH destinations to the plugin and let
 * it pick; this helper is the single source of truth for the mapping so the two
 * destinations stay in sync and are testable without the plugin.
 */
export function magicLinkRedirectTarget(input: {
  hasHousehold: boolean
}): typeof ONBOARDED_DESTINATION | typeof NEW_USER_DESTINATION {
  return input.hasHousehold ? ONBOARDED_DESTINATION : NEW_USER_DESTINATION
}

/**
 * Read the flow back out of the loosely-typed `metadata` the plugin hands to
 * `sendMagicLink`. Defaults to `'approval'` only when nothing usable is present;
 * callers always set `flow` explicitly, so this is just a safe narrowing.
 */
export function readMagicLinkMetadata(metadata: unknown): MagicLinkMetadata {
  if (metadata && typeof metadata === 'object') {
    const m = metadata as Record<string, unknown>
    const flow = m.flow === 'otp' ? 'otp' : 'approval'
    const otp = typeof m.otp === 'string' ? m.otp : undefined
    return { flow, otp }
  }
  return { flow: 'approval' }
}
