/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StyleguideRouteImport } from './routes/styleguide'
import { Route as SignOutRouteImport } from './routes/sign-out'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiSimilarRouteImport } from './routes/api/similar'
import { Route as ApiPlanRouteImport } from './routes/api/plan'
import { Route as ApiLogRouteImport } from './routes/api/log'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AdminWhyRouteImport } from './routes/admin/why'
import { Route as AdminWaitlistRouteImport } from './routes/admin/waitlist'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminMatchingRouteImport } from './routes/admin/matching'
import { Route as AdminFeedbackRouteImport } from './routes/admin/feedback'
import { Route as AdminBenchmarkRouteImport } from './routes/admin/benchmark'
import { Route as AuthedWeekRouteImport } from './routes/_authed.week'
import { Route as AuthedShoppingRouteImport } from './routes/_authed.shopping'
import { Route as AuthedAppRouteImport } from './routes/_authed.app'
import { Route as TipIdReturnRouteImport } from './routes/tip.$id.return'
import { Route as RatePlanIdDayRouteImport } from './routes/rate.$planId.$day'
import { Route as ApiVapiToolRouteImport } from './routes/api/vapi/tool'
import { Route as ApiVapiTokenRouteImport } from './routes/api/vapi/token'
import { Route as ApiMollieWebhookRouteImport } from './routes/api/mollie/webhook'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const StyleguideRoute = StyleguideRouteImport.update({
  id: '/styleguide',
  path: '/styleguide',
  getParentRoute: () => rootRouteImport,
} as any)
const SignOutRoute = SignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiSimilarRoute = ApiSimilarRouteImport.update({
  id: '/api/similar',
  path: '/api/similar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlanRoute = ApiPlanRouteImport.update({
  id: '/api/plan',
  path: '/api/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogRoute = ApiLogRouteImport.update({
  id: '/api/log',
  path: '/api/log',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWhyRoute = AdminWhyRouteImport.update({
  id: '/why',
  path: '/why',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminWaitlistRoute = AdminWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMatchingRoute = AdminMatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBenchmarkRoute = AdminBenchmarkRouteImport.update({
  id: '/benchmark',
  path: '/benchmark',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthedWeekRoute = AuthedWeekRouteImport.update({
  id: '/week',
  path: '/week',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedShoppingRoute = AuthedShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAppRoute = AuthedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthedRoute,
} as any)
const TipIdReturnRoute = TipIdReturnRouteImport.update({
  id: '/tip/$id/return',
  path: '/tip/$id/return',
  getParentRoute: () => rootRouteImport,
} as any)
const RatePlanIdDayRoute = RatePlanIdDayRouteImport.update({
  id: '/rate/$planId/$day',
  path: '/rate/$planId/$day',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVapiToolRoute = ApiVapiToolRouteImport.update({
  id: '/api/vapi/tool',
  path: '/api/vapi/tool',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVapiTokenRoute = ApiVapiTokenRouteImport.update({
  id: '/api/vapi/token',
  path: '/api/vapi/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMollieWebhookRoute = ApiMollieWebhookRouteImport.update({
  id: '/api/mollie/webhook',
  path: '/api/mollie/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/styleguide': typeof StyleguideRoute
  '/app': typeof AuthedAppRoute
  '/shopping': typeof AuthedShoppingRoute
  '/week': typeof AuthedWeekRoute
  '/admin/benchmark': typeof AdminBenchmarkRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/matching': typeof AdminMatchingRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/admin/why': typeof AdminWhyRoute
  '/api/health': typeof ApiHealthRoute
  '/api/log': typeof ApiLogRoute
  '/api/plan': typeof ApiPlanRoute
  '/api/similar': typeof ApiSimilarRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/mollie/webhook': typeof ApiMollieWebhookRoute
  '/api/vapi/token': typeof ApiVapiTokenRoute
  '/api/vapi/tool': typeof ApiVapiToolRoute
  '/rate/$planId/$day': typeof RatePlanIdDayRoute
  '/tip/$id/return': typeof TipIdReturnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/styleguide': typeof StyleguideRoute
  '/app': typeof AuthedAppRoute
  '/shopping': typeof AuthedShoppingRoute
  '/week': typeof AuthedWeekRoute
  '/admin/benchmark': typeof AdminBenchmarkRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/matching': typeof AdminMatchingRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/admin/why': typeof AdminWhyRoute
  '/api/health': typeof ApiHealthRoute
  '/api/log': typeof ApiLogRoute
  '/api/plan': typeof ApiPlanRoute
  '/api/similar': typeof ApiSimilarRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/mollie/webhook': typeof ApiMollieWebhookRoute
  '/api/vapi/token': typeof ApiVapiTokenRoute
  '/api/vapi/tool': typeof ApiVapiToolRoute
  '/rate/$planId/$day': typeof RatePlanIdDayRoute
  '/tip/$id/return': typeof TipIdReturnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/_authed': typeof AuthedRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/sign-out': typeof SignOutRoute
  '/styleguide': typeof StyleguideRoute
  '/_authed/app': typeof AuthedAppRoute
  '/_authed/shopping': typeof AuthedShoppingRoute
  '/_authed/week': typeof AuthedWeekRoute
  '/admin/benchmark': typeof AdminBenchmarkRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/matching': typeof AdminMatchingRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/admin/why': typeof AdminWhyRoute
  '/api/health': typeof ApiHealthRoute
  '/api/log': typeof ApiLogRoute
  '/api/plan': typeof ApiPlanRoute
  '/api/similar': typeof ApiSimilarRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/mollie/webhook': typeof ApiMollieWebhookRoute
  '/api/vapi/token': typeof ApiVapiTokenRoute
  '/api/vapi/tool': typeof ApiVapiToolRoute
  '/rate/$planId/$day': typeof RatePlanIdDayRoute
  '/tip/$id/return': typeof TipIdReturnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/discover'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/sign-in'
    | '/sign-out'
    | '/styleguide'
    | '/app'
    | '/shopping'
    | '/week'
    | '/admin/benchmark'
    | '/admin/feedback'
    | '/admin/matching'
    | '/admin/users'
    | '/admin/waitlist'
    | '/admin/why'
    | '/api/health'
    | '/api/log'
    | '/api/plan'
    | '/api/similar'
    | '/admin/'
    | '/api/auth/$'
    | '/api/mollie/webhook'
    | '/api/vapi/token'
    | '/api/vapi/tool'
    | '/rate/$planId/$day'
    | '/tip/$id/return'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/sign-in'
    | '/sign-out'
    | '/styleguide'
    | '/app'
    | '/shopping'
    | '/week'
    | '/admin/benchmark'
    | '/admin/feedback'
    | '/admin/matching'
    | '/admin/users'
    | '/admin/waitlist'
    | '/admin/why'
    | '/api/health'
    | '/api/log'
    | '/api/plan'
    | '/api/similar'
    | '/admin'
    | '/api/auth/$'
    | '/api/mollie/webhook'
    | '/api/vapi/token'
    | '/api/vapi/tool'
    | '/rate/$planId/$day'
    | '/tip/$id/return'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/_authed'
    | '/discover'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/sign-in'
    | '/sign-out'
    | '/styleguide'
    | '/_authed/app'
    | '/_authed/shopping'
    | '/_authed/week'
    | '/admin/benchmark'
    | '/admin/feedback'
    | '/admin/matching'
    | '/admin/users'
    | '/admin/waitlist'
    | '/admin/why'
    | '/api/health'
    | '/api/log'
    | '/api/plan'
    | '/api/similar'
    | '/admin/'
    | '/api/auth/$'
    | '/api/mollie/webhook'
    | '/api/vapi/token'
    | '/api/vapi/tool'
    | '/rate/$planId/$day'
    | '/tip/$id/return'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthedRoute: typeof AuthedRouteWithChildren
  DiscoverRoute: typeof DiscoverRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  SignInRoute: typeof SignInRoute
  SignOutRoute: typeof SignOutRoute
  StyleguideRoute: typeof StyleguideRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiLogRoute: typeof ApiLogRoute
  ApiPlanRoute: typeof ApiPlanRoute
  ApiSimilarRoute: typeof ApiSimilarRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMollieWebhookRoute: typeof ApiMollieWebhookRoute
  ApiVapiTokenRoute: typeof ApiVapiTokenRoute
  ApiVapiToolRoute: typeof ApiVapiToolRoute
  RatePlanIdDayRoute: typeof RatePlanIdDayRoute
  TipIdReturnRoute: typeof TipIdReturnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/styleguide': {
      id: '/styleguide'
      path: '/styleguide'
      fullPath: '/styleguide'
      preLoaderRoute: typeof StyleguideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-out': {
      id: '/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof SignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/similar': {
      id: '/api/similar'
      path: '/api/similar'
      fullPath: '/api/similar'
      preLoaderRoute: typeof ApiSimilarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plan': {
      id: '/api/plan'
      path: '/api/plan'
      fullPath: '/api/plan'
      preLoaderRoute: typeof ApiPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/log': {
      id: '/api/log'
      path: '/api/log'
      fullPath: '/api/log'
      preLoaderRoute: typeof ApiLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/why': {
      id: '/admin/why'
      path: '/why'
      fullPath: '/admin/why'
      preLoaderRoute: typeof AdminWhyRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/waitlist': {
      id: '/admin/waitlist'
      path: '/waitlist'
      fullPath: '/admin/waitlist'
      preLoaderRoute: typeof AdminWaitlistRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/matching': {
      id: '/admin/matching'
      path: '/matching'
      fullPath: '/admin/matching'
      preLoaderRoute: typeof AdminMatchingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/benchmark': {
      id: '/admin/benchmark'
      path: '/benchmark'
      fullPath: '/admin/benchmark'
      preLoaderRoute: typeof AdminBenchmarkRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authed/week': {
      id: '/_authed/week'
      path: '/week'
      fullPath: '/week'
      preLoaderRoute: typeof AuthedWeekRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/shopping': {
      id: '/_authed/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof AuthedShoppingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/app': {
      id: '/_authed/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthedAppRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/tip/$id/return': {
      id: '/tip/$id/return'
      path: '/tip/$id/return'
      fullPath: '/tip/$id/return'
      preLoaderRoute: typeof TipIdReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate/$planId/$day': {
      id: '/rate/$planId/$day'
      path: '/rate/$planId/$day'
      fullPath: '/rate/$planId/$day'
      preLoaderRoute: typeof RatePlanIdDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vapi/tool': {
      id: '/api/vapi/tool'
      path: '/api/vapi/tool'
      fullPath: '/api/vapi/tool'
      preLoaderRoute: typeof ApiVapiToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vapi/token': {
      id: '/api/vapi/token'
      path: '/api/vapi/token'
      fullPath: '/api/vapi/token'
      preLoaderRoute: typeof ApiVapiTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mollie/webhook': {
      id: '/api/mollie/webhook'
      path: '/api/mollie/webhook'
      fullPath: '/api/mollie/webhook'
      preLoaderRoute: typeof ApiMollieWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminBenchmarkRoute: typeof AdminBenchmarkRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminMatchingRoute: typeof AdminMatchingRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWaitlistRoute: typeof AdminWaitlistRoute
  AdminWhyRoute: typeof AdminWhyRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBenchmarkRoute: AdminBenchmarkRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminMatchingRoute: AdminMatchingRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWaitlistRoute: AdminWaitlistRoute,
  AdminWhyRoute: AdminWhyRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAppRoute: typeof AuthedAppRoute
  AuthedShoppingRoute: typeof AuthedShoppingRoute
  AuthedWeekRoute: typeof AuthedWeekRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAppRoute: AuthedAppRoute,
  AuthedShoppingRoute: AuthedShoppingRoute,
  AuthedWeekRoute: AuthedWeekRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthedRoute: AuthedRouteWithChildren,
  DiscoverRoute: DiscoverRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  SignInRoute: SignInRoute,
  SignOutRoute: SignOutRoute,
  StyleguideRoute: StyleguideRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiLogRoute: ApiLogRoute,
  ApiPlanRoute: ApiPlanRoute,
  ApiSimilarRoute: ApiSimilarRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMollieWebhookRoute: ApiMollieWebhookRoute,
  ApiVapiTokenRoute: ApiVapiTokenRoute,
  ApiVapiToolRoute: ApiVapiToolRoute,
  RatePlanIdDayRoute: RatePlanIdDayRoute,
  TipIdReturnRoute: TipIdReturnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
